### ISSUE TITLE
need clarification

### ISSUE THREAD

**Issue by ckot** [wq/django-swappable-models#11]
**EDIT** totally re-written for reasons of brevity and clarity

This is a _possible_ duplicate of issue #10, but it wasn't written in a way which was concrete enough for me to be sure.  I'll try and make this as concrete and minimal as possible.  I have 3 questions (below).

 Consider `reusableapp` which consists of

**reusableapp/models.py**

```
from django.db import models
import swapper

class FooBase(models.Model):
    some_field = models.CharField(max_length=32)

    class Meta:
        abstract = True


class Foo(FooBase):
    # default (swappable) implementation of FooBase
    class Meta:
        swappable = swapper.swappable_setting("reusableapp", "Foo")
```

**reusableapp/migrations/0001_initial.py**

```
from __future__ import unicode_literals

from django.db import migrations, models
import swapper


class Migration(migrations.Migration):

    dependencies = [
        swapper.dependency('reusableapp', 'Foo')
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('some_field', models.CharField(max_length=32)),
            ],
            options={
                'swappable': swapper.swappable_setting("reusableapp", "Foo"),
            },
        ),
    ]
```

and 'myapp' which only consists of:

**myapp/models.py**

```
from django.db import models
from reusableapp.models import FooBase

class Bar(models.Model):
    name = models.CharField(max_length=32)

class Foo(FooBase):
         bar = models.ForeignKey('Bar', related_name='foo', null=True)
```

**question 1** should myapp/model.py:Foo also have:

```
       class Meta:
           swappable = swapper.swappable_setting("reusableapp", "Foo")
```

I _think_ the answer is `yes`, as I don't see why this implementation is any different than the `default` implementation in `reusableapp`.  Also, I seem to get field lookup errors, as mentioned in issue #10  if this isn't declared.

**question 2** does the migration for myapp which introduces it's own implementation of `FooBase` need to be updated to use `swapper` instead of `settings` as in `reusableapp/migrations/0001_initial.py`?

**question 3** if the answer to question 2 is `yes`, should it declare:

```
   dependencies = [
      swapper.dependency("reusableapp", "Foo")
   ]
```

**Comment by sheppard** [comment]
Thanks for the report.  This is a different set of questions than #10.  Here are my responses:
 - **question 1**: No, the `swappable` Meta attribute should only be set on the default model (reusableapp.Foo).  The purpose of the attribute is to notify Django that the model might be swapped for another model.  The actual swapping happens when you set `REUSABLEAPP_FOO_MODEL = 'myapp.Foo'` in settings.py.
 - **question 2**: You can modify the migrations for myapp if you want, but in general you shouldn't have to.  The goal is to make it as easy as possible for anyone implementing their own `myapp` to integrate your `reusableapp` with just a subclass and a setting - the less they have to dig around in migrations the better.  (In practice, there are [edge cases](https://github.com/wq/vera) that do require manually modifying myapp's migrations - but not in this case).
 - **question 3**: This shouldn't hurt anything, but I would actually recommend not doing this for reasons similar to question 1.  When you (or anyone) implement a project-specific `myapp`, you already know that you're going to swap out `reusableapp.Foo` for `myapp.Foo`, and [explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/).  If anything, you could add this:

   ```python
       dependencies = [
           ('myapp', '0001_initial'),
       ]
   ```
But in this case, you're already in the first myapp migration so you don't need a dependency to it.

The important concept to keep in mind is that `reusableapp` and `myapp` are usually implemented by people in different roles - the first by an author of a shared library, the second by a developer implementing a single website.  In practice, you might be doing both, but it helps to mentally separate these roles when you implement the project.  I'll add some more notes about this to the documentation.

**Comment by blag** [comment]
1. No, for the exact reason @sheppard mentioned.

Your `reusableapp/migrations/0001_initial.py` should not have the circular dependency in it. Remove it like so:

```diff
     dependencies = [
-        swapper.dependency('reusableapp', 'Foo')
     ]
```
